#!/usr/bin/env bash
wget https://gist.github.com/tommy19970714/29488251b8b88aa1fee0b7881388f40a/raw/ -O /self-supervised-speech-recognition/config/pretraining/wav2vec2_base_librispeech.yaml

sh copy_checkpoints.sh & 
last_checkpoint="/opt/ml/checkpoints/checkpoint_last.pt"
if [ -e $last_checkpoint ]; then
  echo "Restore from checkpoint"
  echo "Restore from checkpoint" > /opt/ml/checkpoints/msg.txt
  python pretrain.py --fairseq_path libs/fairseq --audio_path /opt/ml/input/data/training --init_model $last_checkpoint 
else
  echo "Start from wav2vec_small.pt"
  wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt /self-supervised-speech-recognition/wav2vec_small.pt
  python pretrain.py --fairseq_path libs/fairseq --audio_path /opt/ml/input/data/training --init_model /self-supervised-speech-recognition/wav2vec_small.pt 
fi

